### ISSUE TITLE
hackerNews 拉取失败

### ISSUE THREAD

**Issue by loqiu** [Mayandev/hacker-feeds-cli#1]
hackerNews 拉取信息失败
![image](https://user-images.githubusercontent.com/35633174/120280917-e2509600-c2ea-11eb-926b-b2ccbc59b9a1.png)
网站提示
![image](https://user-images.githubusercontent.com/35633174/120280995-00b69180-c2eb-11eb-8993-86b86d2d9930.png)

**Comment by Mayandev** [comment]
应该是你这边的网络问题
