### ISSUE TITLE
Error: connect ETIMEDOUT

### ISSUE THREAD

**Issue by Kingson** [Mayandev/hacker-feeds-cli#2]
数据拉取失败
![image](https://user-images.githubusercontent.com/468509/120683065-c3f7bf80-c4cf-11eb-8c05-ca5d69e891e4.png)

**Comment by Mayandev** [comment]
我这边无法复现，请问你是否开了任何代理？你可以先尝试访问 [https://www.v2ex.com](https://www.v2ex.com)，看是否能够打开。

**Comment by Kingson** [comment]
> 我这边无法复现，请问你是否开了任何代理？你可以先尝试访问 https://www.v2ex.com，看是否能够打开。

是开了代理，访问v2ex没问题，实际上其他的也报数据拉取失败

**Comment by Mayandev** [comment]
> > 我这边无法复现，请问你是否开了任何代理？你可以先尝试访问 [https://www.v2ex.com，看是否能够打开。](https://www.v2ex.com%EF%BC%8C%E7%9C%8B%E6%98%AF%E5%90%A6%E8%83%BD%E5%A4%9F%E6%89%93%E5%BC%80%E3%80%82)
> 
> 是开了代理，访问v2ex没问题，实际上其他的也报数据拉取失败

能否复制一下终端的报错信息

**Comment by lostplesed** [comment]
我也是拉取不到数据，是否需要配置代理，终端应该是没有走代理的。


(base) ➜  ~ hf v2ex
⠙ 数据拉取中...Error: connect ETIMEDOUT 59.24.3.173:443
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1128:16) {
  errno: -60,
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '59.24.3.173',
  port: 443,
  config: {
    url: 'https://www.v2ex.com/api/topics/show.json?node_name=create',
    method: 'get',
    headers: {
      Accept: 'application/json, text/plain, */*',
      'User-Agent': 'axios/0.21.1'
    },
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    adapter: [Function: httpAdapter],
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    validateStatus: [Function: validateStatus],
    data: undefined
  },
  request: <ref *1> Writable {
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      constructed: true,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      errored: null,
      closed: false,
      closeEmitted: false,
      [Symbol(kOnFinished)]: []
    },
    _events: [Object: null prototype] {
      response: [Function: handleResponse],
      error: [Function: handleRequestError]
    },
    _eventsCount: 2,
    _maxListeners: undefined,
    _options: {
      maxRedirects: 21,
      maxBodyLength: 10485760,
      protocol: 'https:',
      path: '/api/topics/show.json?node_name=create',
      method: 'GET',
      headers: [Object],
      agent: undefined,
      agents: [Object],
      auth: undefined,
      hostname: 'www.v2ex.com',
      port: null,
      nativeProtocols: [Object],
      pathname: '/api/topics/show.json',
      search: '?node_name=create'
    },
    _ended: true,
    _ending: true,
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 0,
    _requestBodyBuffers: [],
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: [TLSSocket],
      _header: 'GET /api/topics/show.json?node_name=create HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'User-Agent: axios/0.21.1\r\n' +
        'Host: www.v2ex.com\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/api/topics/show.json?node_name=create',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'www.v2ex.com',
      protocol: 'https:',
      _redirectable: [Circular *1],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    _currentUrl: 'https://www.v2ex.com/api/topics/show.json?node_name=create',
    [Symbol(kCapture)]: false
  },
  response: undefined,
  isAxiosError: true,
  toJSON: [Function: toJSON]
}

**Comment by lostplesed** [comment]
终端开启代理后也是报错，前面有些不一样的错误信息。

export https_proxy=http://127.0.0.1:7890 http_proxy=http://127.0.0.1:7890 all_proxy=socks5://127.0.0.1:7890
(base) ➜  ~ hf v2ex
⠼ 数据拉取中...Error: Client network socket disconnected before secure TLS connection was established
    at connResetException (node:internal/errors:629:14)
    at TLSSocket.onConnectEnd (node:_tls_wrap:1545:19)
    at TLSSocket.emit (node:events:341:22)
    at endReadableNT (node:internal/streams/readable:1294:12)
    at processTicksAndRejections (node:internal/process/task_queues:80:21) {
  code: 'ECONNRESET',
  path: null,
  host: '127.0.0.1',
  port: '7890',
  localAddress: undefined,
  config: {
    url: 'https://www.v2ex.com/api/topics/show.json?node_name=create',
    method: 'get',
    headers: {
      Accept: 'application/json, text/plain, */*',
      'User-Agent': 'axios/0.21.1',
      host: 'www.v2ex.com'
    },
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    adapter: [Function: httpAdapter],
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    validateStatus: [Function: validateStatus],
    data: undefined
  },
  request: <ref *1> Writable {
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      constructed: true,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      errored: null,
      closed: false,
      closeEmitted: false,
      [Symbol(kOnFinished)]: []
    },
    _events: [Object: null prototype] {
      response: [Function: handleResponse],
      error: [Function: handleRequestError]
    },
    _eventsCount: 2,
    _maxListeners: undefined,
    _options: {
      maxRedirects: 21,
      maxBodyLength: 10485760,
      protocol: 'https:',
      path: 'https://www.v2ex.com/api/topics/show.json?node_name=create',
      method: 'GET',
      headers: [Object],
      agent: undefined,
      agents: [Object],
      auth: null,
      hostname: '127.0.0.1',
      port: '7890',
      beforeRedirect: [Function: beforeRedirect],
      nativeProtocols: [Object],
      pathname: '/api/topics/show.json',
      search: '?node_name=create',
      slashes: true,
      hash: null,
      query: 'node_name=create',
      href: 'https://www.v2ex.com/api/topics/show.json?node_name=create'
    },
    _ended: true,
    _ending: true,
    _redirectCount: 1,
    _redirects: [],
    _requestBodyLength: 0,
    _requestBodyBuffers: [],
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: [TLSSocket],
      _header: 'GET https://www.v2ex.com/api/topics/show.json?node_name=create HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'User-Agent: axios/0.21.1\r\n' +
        'host: www.v2ex.com\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: 'https://www.v2ex.com/api/topics/show.json?node_name=create',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: '127.0.0.1',
      protocol: 'https:',
      _redirectable: [Circular *1],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    _currentUrl: 'https://127.0.0.1:7890/api/topics/show.json?node_name=create',
    _isRedirect: true,
    [Symbol(kCapture)]: false
  },
  response: undefined,
  isAxiosError: true,
  toJSON: [Function: toJSON]
}
✖ 程序错误, 你可以发送邮件至 <phillzou@gmail.com> 联系开发者
(base) ➜  ~ hf v2ex
⠹ 数据拉取中...Error: Client network socket disconnected before secure TLS connection was established
    at connResetException (node:internal/errors:629:14)
    at TLSSocket.onConnectEnd (node:_tls_wrap:1545:19)
    at TLSSocket.emit (node:events:341:22)
    at endReadableNT (node:internal/streams/readable:1294:12)
    at processTicksAndRejections (node:internal/process/task_queues:80:21) {
  code: 'ECONNRESET',
  path: null,
  host: '127.0.0.1',
  port: '7890',
  localAddress: undefined,
  config: {
    url: 'https://www.v2ex.com/api/topics/show.json?node_name=create',
    method: 'get',
    headers: {
      Accept: 'application/json, text/plain, */*',
      'User-Agent': 'axios/0.21.1',
      host: 'www.v2ex.com'
    },
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    adapter: [Function: httpAdapter],
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    validateStatus: [Function: validateStatus],
    data: undefined
  },
  request: <ref *1> Writable {
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      constructed: true,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      errored: null,
      closed: false,
      closeEmitted: false,
      [Symbol(kOnFinished)]: []
    },
    _events: [Object: null prototype] {
      response: [Function: handleResponse],
      error: [Function: handleRequestError]
    },
    _eventsCount: 2,
    _maxListeners: undefined,
    _options: {
      maxRedirects: 21,
      maxBodyLength: 10485760,
      protocol: 'https:',
      path: 'https://www.v2ex.com/api/topics/show.json?node_name=create',
      method: 'GET',
      headers: [Object],
      agent: undefined,
      agents: [Object],
      auth: null,
      hostname: '127.0.0.1',
      port: '7890',
      beforeRedirect: [Function: beforeRedirect],
      nativeProtocols: [Object],
      pathname: '/api/topics/show.json',
      search: '?node_name=create',
      slashes: true,
      hash: null,
      query: 'node_name=create',
      href: 'https://www.v2ex.com/api/topics/show.json?node_name=create'
    },
    _ended: true,
    _ending: true,
    _redirectCount: 1,
    _redirects: [],
    _requestBodyLength: 0,
    _requestBodyBuffers: [],
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: [TLSSocket],
      _header: 'GET https://www.v2ex.com/api/topics/show.json?node_name=create HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'User-Agent: axios/0.21.1\r\n' +
        'host: www.v2ex.com\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: 'https://www.v2ex.com/api/topics/show.json?node_name=create',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: '127.0.0.1',
      protocol: 'https:',
      _redirectable: [Circular *1],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    _currentUrl: 'https://127.0.0.1:7890/api/topics/show.json?node_name=create',
    _isRedirect: true,
    [Symbol(kCapture)]: false
  },
  response: undefined,
  isAxiosError: true,
  toJSON: [Function: toJSON]
}
✖ 程序错误, 你可以发送邮件至 <phillzou@gmail.com> 联系开发者
(base) ➜  ~

**Comment by Duan-JM** [comment]
** My Enviroments:**
- macOS 11.4
- MacBook Air M1 2020
- iTerm
- Zsh
- npm version: 7.10.0

**My operations:**
```bash
hfeeds news -t 10    
```
**Some checks:**
- [x] Can visit hack news
- [x] Run into the same issue with Proxy
- [x] Run  into the same issue without Proxy
- [x] Same issue for Github

**Same issue:**
```bash
⠴ Fetching feeds...Error: connect ETIMEDOUT 35.201.97.85:443
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1133:16) {
  errno: -60,
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '35.201.97.85',
  port: 443,
  config: {
    url: 'https://hacker-news.firebaseio.com/v0/topstories.json',
    method: 'get',
    headers: {
      Accept: 'application/json, text/plain, */*',
      'User-Agent': 'axios/0.21.1'
    },
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    adapter: [Function: httpAdapter],
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    validateStatus: [Function: validateStatus],
    data: undefined
  },
  request: <ref *1> Writable {
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      constructed: true,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      errored: null,
      closed: false,
      closeEmitted: false,
      [Symbol(kOnFinished)]: []
    },
    _events: [Object: null prototype] {
      response: [Function: handleResponse],
      error: [Function: handleRequestError]
    },
    _eventsCount: 2,
    _maxListeners: undefined,
    _options: {
      maxRedirects: 21,
      maxBodyLength: 10485760,
      protocol: 'https:',
      path: '/v0/topstories.json',
      method: 'GET',
      headers: [Object],
      agent: undefined,
      agents: [Object],
      auth: undefined,
      hostname: 'hacker-news.firebaseio.com',
      port: null,
      nativeProtocols: [Object],
      pathname: '/v0/topstories.json'
    },
    _ended: true,
    _ending: true,
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 0,
    _requestBodyBuffers: [],
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: [TLSSocket],
      _header: 'GET /v0/topstories.json HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'User-Agent: axios/0.21.1\r\n' +
        'Host: hacker-news.firebaseio.com\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/v0/topstories.json',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'hacker-news.firebaseio.com',
      protocol: 'https:',
      _redirectable: [Circular *1],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    _currentUrl: 'https://hacker-news.firebaseio.com/v0/topstories.json',
    [Symbol(kCapture)]: false
  },
  response: undefined,
  isAxiosError: true,
  toJSON: [Function: toJSON]
}
✖ Something error, You can contact the developer. Mail to <phillzou@gmail.com>
```

**Comment by jacklanda** [comment]
同样的报错+1

**Comment by DeepRolling** [comment]
+1

**Comment by Mayandev** [comment]
> ** My Enviroments:**
> 
> * macOS 11.4
> * MacBook Air M1 2020
> * iTerm
> * Zsh
> * npm version: 7.10.0
> 
> **My operations:**
> 
> ```shell
> hfeeds news -t 10    
> ```
> 
> **Some checks:**
> 
> * [x]  Can visit hack news
> * [x]  Run into the same issue with Proxy
> * [x]  Run  into the same issue without Proxy
> * [x]  Same issue for Github
> 
> **Same issue:**
> 
> ```shell
> ⠴ Fetching feeds...Error: connect ETIMEDOUT 35.201.97.85:443
>     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1133:16) {
>   errno: -60,
>   code: 'ETIMEDOUT',
>   syscall: 'connect',
>   address: '35.201.97.85',
>   port: 443,
>   config: {
>     url: 'https://hacker-news.firebaseio.com/v0/topstories.json',
>     method: 'get',
>     headers: {
>       Accept: 'application/json, text/plain, */*',
>       'User-Agent': 'axios/0.21.1'
>     },
>     transformRequest: [ [Function: transformRequest] ],
>     transformResponse: [ [Function: transformResponse] ],
>     timeout: 0,
>     adapter: [Function: httpAdapter],
>     xsrfCookieName: 'XSRF-TOKEN',
>     xsrfHeaderName: 'X-XSRF-TOKEN',
>     maxContentLength: -1,
>     maxBodyLength: -1,
>     validateStatus: [Function: validateStatus],
>     data: undefined
>   },
>   request: <ref *1> Writable {
>     _writableState: WritableState {
>       objectMode: false,
>       highWaterMark: 16384,
>       finalCalled: false,
>       needDrain: false,
>       ending: false,
>       ended: false,
>       finished: false,
>       destroyed: false,
>       decodeStrings: true,
>       defaultEncoding: 'utf8',
>       length: 0,
>       writing: false,
>       corked: 0,
>       sync: true,
>       bufferProcessing: false,
>       onwrite: [Function: bound onwrite],
>       writecb: null,
>       writelen: 0,
>       afterWriteTickInfo: null,
>       buffered: [],
>       bufferedIndex: 0,
>       allBuffers: true,
>       allNoop: true,
>       pendingcb: 0,
>       constructed: true,
>       prefinished: false,
>       errorEmitted: false,
>       emitClose: true,
>       autoDestroy: true,
>       errored: null,
>       closed: false,
>       closeEmitted: false,
>       [Symbol(kOnFinished)]: []
>     },
>     _events: [Object: null prototype] {
>       response: [Function: handleResponse],
>       error: [Function: handleRequestError]
>     },
>     _eventsCount: 2,
>     _maxListeners: undefined,
>     _options: {
>       maxRedirects: 21,
>       maxBodyLength: 10485760,
>       protocol: 'https:',
>       path: '/v0/topstories.json',
>       method: 'GET',
>       headers: [Object],
>       agent: undefined,
>       agents: [Object],
>       auth: undefined,
>       hostname: 'hacker-news.firebaseio.com',
>       port: null,
>       nativeProtocols: [Object],
>       pathname: '/v0/topstories.json'
>     },
>     _ended: true,
>     _ending: true,
>     _redirectCount: 0,
>     _redirects: [],
>     _requestBodyLength: 0,
>     _requestBodyBuffers: [],
>     _onNativeResponse: [Function (anonymous)],
>     _currentRequest: ClientRequest {
>       _events: [Object: null prototype],
>       _eventsCount: 7,
>       _maxListeners: undefined,
>       outputData: [],
>       outputSize: 0,
>       writable: true,
>       destroyed: false,
>       _last: true,
>       chunkedEncoding: false,
>       shouldKeepAlive: false,
>       _defaultKeepAlive: true,
>       useChunkedEncodingByDefault: false,
>       sendDate: false,
>       _removedConnection: false,
>       _removedContLen: false,
>       _removedTE: false,
>       _contentLength: 0,
>       _hasBody: true,
>       _trailer: '',
>       finished: true,
>       _headerSent: true,
>       _closed: false,
>       socket: [TLSSocket],
>       _header: 'GET /v0/topstories.json HTTP/1.1\r\n' +
>         'Accept: application/json, text/plain, */*\r\n' +
>         'User-Agent: axios/0.21.1\r\n' +
>         'Host: hacker-news.firebaseio.com\r\n' +
>         'Connection: close\r\n' +
>         '\r\n',
>       _keepAliveTimeout: 0,
>       _onPendingData: [Function: nop],
>       agent: [Agent],
>       socketPath: undefined,
>       method: 'GET',
>       maxHeaderSize: undefined,
>       insecureHTTPParser: undefined,
>       path: '/v0/topstories.json',
>       _ended: false,
>       res: null,
>       aborted: false,
>       timeoutCb: null,
>       upgradeOrConnect: false,
>       parser: null,
>       maxHeadersCount: null,
>       reusedSocket: false,
>       host: 'hacker-news.firebaseio.com',
>       protocol: 'https:',
>       _redirectable: [Circular *1],
>       [Symbol(kCapture)]: false,
>       [Symbol(kNeedDrain)]: false,
>       [Symbol(corked)]: 0,
>       [Symbol(kOutHeaders)]: [Object: null prototype]
>     },
>     _currentUrl: 'https://hacker-news.firebaseio.com/v0/topstories.json',
>     [Symbol(kCapture)]: false
>   },
>   response: undefined,
>   isAxiosError: true,
>   toJSON: [Function: toJSON]
> }
> ✖ Something error, You can contact the developer. Mail to <phillzou@gmail.com>
> ```

Thx for the feedback，you provide a nice issue template. As far as I can tell, I think the problem is caused by your network environment，because most of the web servers are located abroad. You can try pinging the following domains.

```console
ping github.com
ping www.v2ex.com
ping hacker-news.firebaseio.com
ping api.producthunt.com
ping www.reddit.com
```

**Comment by Duan-JM** [comment]
**My CheckList:**
- [x] ping github.com
- [ ] ping www.v2ex.com
- [ ] ping hacker-news.firebaseio.com
- [ ] ping api.producthunt.com
- [ ] ping www.reddit.com

Indeed, it caused by my network environment. I can only successfully ping github.com, even with the vpn. I will try to solve my network problem. Thanks for your time~ It is a really interesting tool~
